[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=warn

[program:dbus]
command=dbus-daemon --system --nofork
autostart=true
autorestart=true
priority=1

[program:xvfb]
command=Xvfb :1 -screen 0 %(ENV_RESOLUTION)s -ac +extension GLX +render -noreset
autostart=true
autorestart=true
priority=2
environment=DISPLAY=":1"

[program:x11vnc]
command=x11vnc -display :1 -rfbauth /root/.vnc/passwd -rfbport %(ENV_VNC_PORT)s -forever -shared -noxdamage -quiet
autostart=true
autorestart=true
priority=3
startsecs=3

[program:xfce4]
command=startxfce4
autostart=true
autorestart=true
priority=4
startsecs=3
environment=DISPLAY=":1",HOME="/root",USER="root"

[program:novnc]
command=websockify --web=/usr/share/novnc --heartbeat=30 %(ENV_PORT)s localhost:%(ENV_VNC_PORT)s
autostart=true
autorestart=true
priority=5
startsecs=5
